version: "3.8"

services:

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn api:app --host 0.0.0.0 --port 6500
    volumes:
      - ./backend:/app
      - /home/smillburn/Documents/conductor-441120-b2b06a8ce1c6.json:/app/conductor-441120-b2b06a8ce1c6.json
    environment: 
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "6500:6500"

  frontend:
    build:
      context: frontend 
      dockerfile: Dockerfile
    ports:
      - "3200:8080"
    environment:
      - REACT_APP_API_HOST=http://localhost:6500
